### ISSUE TITLE
Logo competition!

### ISSUE THREAD

**Issue by Cheukting** [Cheukting/picknmix#15]
## Logo competition!

* deadline of submission: 25th June

### Description

It's a competition to win the best logo design for this package. The winning design will be the official logo of this package. I am going to Europython on 7th July and wish to have some kick ass stickers of a beautiful logo to promote this open-source package.

This is a open-source project, your contribution is needed!

### Reward

You will be credited on the contribution page, the readme page and the front page of the documentation. Also, you will received a bunch of stickers with your proudly designed logo.

### How to enter

Send a pull request to the 'logo_competition' branch with your logo stored in the 'logo' directory. File in '.svg' format is preferred.

**Comment by percevalve** [comment]
Have you found a logo ? I know a graphist interested to create one, but only Wednesday. Let me now if this is too late.

**Comment by Cheukting** [comment]
It's never too late! It may not be able to be printed for EuroPython but I will be going to PyData London and PyCon UK so it will still be very helpful. I promise to give the designer a bunch of stickers as well. I can be reached by email or twitter as cheukting_ho

**Comment by Cheukting** [comment]
Thanks Agathe (agathests.com) for the logo
