### ISSUE TITLE
No oof values?

### ISSUE THREAD

**Issue by MarcoGorelli** [Cheukting/picknmix#16]
* Pick n Mix version: 0.1.1
* Python version: 3.7.3 
* Operating System: Ubuntu Linux 64-bit 

### Description
I'm not sure I understand how this library implements stacking. What definition of stacking does it follow?

It seems to me like it does the following, given `train_data`, `train_target`, and `test_data`:
- fit each model in the base layer to `train_data` and `train_target`
- create two new dataframes: one with the predictions of the fitted models on `train_data` (let's call this `l1_train`), and another with the predictions of the fitted models on `test_data` (let's call this `l1_test`)
- fit the model(s) in the next layer on `l1_train` and `train_target`.

I'm not sure this fits the definition of 'stacking' given here http://blog.kaggle.com/2016/12/27/a-kagglers-guide-to-model-stacking-in-practice/ , where they instruct you to use the _out of fold_ predictions from the base models to train the models in the next layer.

### What I Did

```
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from picknmix import Layer, Stack
from sklearn.linear_model import LinearRegression, Ridge
import numpy as np

# load data
boston = load_boston()
data = boston.data
target = boston.target
train_data, test_data, train_target, test_target = train_test_split(data, target, random_state=42)

# picknmix stacking
first_layer = Layer([LinearRegression(), Ridge()])
second_layer = Layer([LinearRegression()])
model = Stack([first_layer, second_layer])
model.fit(train_data, train_target)

# my attempt at matching picknmix by hand
lr = LinearRegression()
lr.fit(train_data, train_target)
rdg = Ridge()
rdg.fit(train_data, train_target)
l1_train = np.array([lr.predict(train_data), rdg.predict(train_data)]).T
l1_test = np.array([lr.predict(test_data), rdg.predict(test_data)]).T
second_lr = LinearRegression()
second_lr.fit(l1_train, train_target)

assert np.allclose(model.predict(test_data), second_lr.predict(l1_test))
```

**Comment by Cheukting** [comment]
Right now it does not support using out of fold to train the next layer, one of the draw back of stacking is if you don't have a lot of data then it is difficult to train a stack with lots of layers using out of fold. It would be nice to have an option for people to switch between the two though. Suggestions are welcome.

**Comment by MarcoGorelli** [comment]
My suggestion would be to add this option :)

Otherwise, you risk overfitting - see https://github.com/vecxoz/vecstack#8-why-do-i-need-complicated-inner-procedure-for-stacking for an example, as well as for a library which does something similar

**Comment by Cheukting** [comment]
Sure, I will have a think about how to implement it. Thanks for your suggestion and you are more then welcome to implement it and send a PR. Highly appreciated!
